AutoParkWeb/Controllers/VehicleTypeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using AutoParkData.Model.Vehicles;
using AutoParkData.Repositories.Interfaces;
using AutoParkWeb.Models.ViewModels;
using AutoParkWeb.Services;
using Microsoft.VisualBasic.CompilerServices;

namespace AutoParkWeb.Controllers
{
    public class VehicleTypeController : Controller
    {
        private readonly IVehicleTypeRepository vehicleTypeRepository;
        private readonly IJsonDeserializationService deserializationService;
        public VehicleTypeController(IVehicleTypeRepository vehicleTypeRepository, IJsonDeserializationService deserializationService)
        {
            this.vehicleTypeRepository = vehicleTypeRepository;
            this.deserializationService = deserializationService;
        }

        public async Task<IActionResult> List()
        {
            var data = await vehicleTypeRepository.GetVehicleTypes();
            return View(data);
        }
        
        [HttpGet]
        public IActionResult Add()
        {
            return View(new VehicleType());
        }

        [HttpPost]
        public async Task<IActionResult> Add(VehicleType vehicleType)
        {
            await vehicleTypeRepository.Add(vehicleType);
            return RedirectToAction(nameof(List));
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var vehicleType = await vehicleTypeRepository.Get(id);
            return View(vehicleType);
        }

        [HttpPost]
        public async Task<IActionResult> Update(VehicleType vehicleType)
        {
            await vehicleTypeRepository.Update(vehicleType);
            return RedirectToAction(nameof(List));
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            await vehicleTypeRepository.Delete(id);
            return RedirectToAction(nameof(List));
        }

        [HttpGet]
        public IActionResult FromJson()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> FromJson(JsonFileViewModel viewModel)
        {
            var vehicleTypes = await deserializationService.ReadVehicleTypes(viewModel.File);
            await vehicleTypeRepository.AddRange(vehicleTypes);
            return RedirectToAction(nameof(List));
        }
    }
}

AutoParkWeb/Views/VehicleType/Add.cshtml
@model VehicleType
@{
    ViewData["Title"] = "Add - Vehicle type";
}


<div class="card">
    <div class="card-header"><h3>Add vehicle type</h3></div>
    <div class="card-body">
        <form asp-controller="VehicleType" asp-action="Add" method="post">

            <div><span asp-validation-for="TaxCoefficient" class="text-danger"></span></div>
            <div class="form-group row">
                <label asp-for="TaxCoefficient" class="col-sm-3 col-form-label"></label>
                <div class="col-sm-9">
                    <input asp-for="TaxCoefficient" class="form-control">
                </div>
            </div>

            <div><span asp-validation-for="TypeName" class="text-danger"></span></div>
            <div class="form-group row">
                <label asp-for="TypeName" class="col-sm-3 col-form-label"></label>
                <div class="col-sm-9">
                    <input asp-for="TypeName" class="form-control">
                </div>
            </div>

            <div class="text-center">
                <button class="btn btn-primary mx-auto">Add</button>
            </div>
        </form>
    </div>
</div>

AutoParkWeb/Views/VehicleType/FromJson.cshtml
@model JsonFileViewModel

@{
    ViewData["Title"] = "Add vehicles types - Json";
}



<div class="card">
    <div class="card-header"><h3>Add vehicle types</h3></div>
    <div class="card-body">
        <form asp-controller="VehicleType" asp-action="FromJson" method="post" enctype="multipart/form-data">

            <div><span asp-validation-for="File" class="text-danger"></span></div>
            <div class="form-group row">
                <label asp-for="File" class="col-sm-3 col-form-label"></label>
                <div class="col-sm-9">
                    <input asp-for="File" class="form-control">
                </div>
            </div>

            <div class="text-center">
                <button class="btn btn-primary mx-auto">Add</button>
            </div>
        </form>
    </div>
</div>

AutoParkWeb/Views/VehicleType/List.cshtml
@using System.Linq
@model IEnumerable<VehicleType>
@{
    ViewData["Title"] = "Vehicle Types";
}

<table class="table">

    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">TypeName</th>
            <th scope="col">TaxCoefficient</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td><strong>@item.Id</strong></td>
                <td>@item.TypeName</td>
                <td>@item.TaxCoefficient</td>
                <td>
                    <form method="post" class="d-inline">
                        <button class="btn btn-sm btn-outline-danger"
                                asp-controller="VehicleType" asp-action="Delete" asp-route-id="@item.Id">
                            Delete
                        </button>
                    </form>
                    <a class="btn btn-sm btn-outline-primary"
                       asp-controller="VehicleType" asp-action="Update" asp-route-id="@item.Id">Update</a>
                </td>
            </tr>
        }
    </tbody>
    <caption>
        To add new item press
        <a class="btn btn-sm btn-primary" asp-controller="VehicleType" asp-action="Add">Add</a>
        or use Json
        <a class="btn btn-sm btn-primary" asp-controller="VehicleType" asp-action="FromJson">Add Json</a>
    </caption>
</table>

AutoParkWeb/Views/VehicleType/Update.cshtml
@model VehicleType
@{
    ViewData["Title"] = "Update - vehicle type";
}

<div class="card">
    <div class="card-header"><h3>Update vehicle type</h3></div>
    <div class="card-body">
        <form asp-controller="VehicleType" asp-action="Update">
            <input asp-for="Id" hidden>

            <div><span asp-validation-for="TaxCoefficient" class="text-danger"></span></div>
            <div class="form-group row">
                <label asp-for="TaxCoefficient" class="col-sm-3 col-form-label"></label>
                <div class="col-sm-9">
                    <input asp-for="TaxCoefficient" class="form-control">
                </div>
            </div>

            <div><span asp-validation-for="TypeName" class="text-danger"></span></div>
            <div class="form-group row">
                <label asp-for="TypeName" class="col-sm-3 col-form-label"></label>
                <div class="col-sm-9">
                    <input asp-for="TypeName" class="form-control">
                </div>
            </div>

            <div class="text-center">
                <button class="btn btn-block btn-primary mx-auto">Update</button>
            </div>
        </form>
    </div>
</div>