AutoParkWeb/Controllers/SparePartController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoParkData.Model.Orders;
using AutoParkData.Repositories.Interfaces;

namespace AutoParkWeb.Controllers
{
    public class SparePartController : Controller
    {
        private readonly ISparePartRepository repository;

        public SparePartController(ISparePartRepository repository)
        {
            this.repository = repository;
        }

        public async Task<IActionResult> List()
        {
            var spareParts = await repository.GetSpareParts();
            return View(spareParts);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View(new SparePart());
        }

        [HttpPost]
        public async Task<IActionResult> Add(SparePart sparePart)
        {
            if (ModelState.IsValid)
            {
                await repository.Add(sparePart);
                return RedirectToAction(nameof(List));
            }

            return View(sparePart);
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var sparePart = await repository.Get(id);
            return View(sparePart);
        }

        [HttpPost]
        public async Task<IActionResult> Update(SparePart sparePart)
        {
            await repository.Update(sparePart);
            return RedirectToAction(nameof(List));
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            await repository.Delete(id);
            return RedirectToAction(nameof(List));
        }
    }
}

AutoParkWeb/Views/SparePart/Add.cshtml
@model SparePart
@{
    ViewData["Title"] = "Add - Spare part";
}

<div class="card">
    <div class="card-header"><h3>Add vehicle type</h3></div>
    <div class="card-body">
        <div asp-validation-summary="All" class="text-danger"></div>

        <form asp-controller="SparePart" asp-action="Add" method="post">

            <div><span asp-validation-for="Name" class="text-danger"></span></div>
            <div class="form-group row">
                <div><span asp-validation-for="Name" class="text-danger"></span></div>
                <label asp-for="Name" class="col-sm-3 col-form-label"></label>
                <div class="col-sm-9">
                    <input asp-for="Name" class="form-control">
                </div>
            </div>

            <div><span asp-validation-for="Description" class="text-danger"></span></div>
            <div class="form-group row">
                <div><span asp-validation-for="Description" class="text-danger"></span></div>
                <label asp-for="Description" class="col-sm-3 col-form-label"></label>
                <div class="col-sm-9">
                    <input asp-for="Description" class="form-control">
                </div>
            </div>

            <div class="text-center">
                <button class="btn btn-primary mx-auto">Add</button>
            </div>
        </form>
    </div>
</div>

AutoParkWeb/Views/SparePart/List.cshtml
@model IEnumerable<SparePart>
@{
    ViewData["Title"] = "Spare parts";
}

<table class="table">

    <thead>
    <tr>
        <th scope="col">Id</th>
        <th scope="col">Name</th>
        <th scope="col">Description</th>
        <th scope="col">Actions</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td><strong>@item.Id</strong></td>
            <td>@item.Name</td>
            <td>@item.Description</td>
            <td>
                <form method="post" class="d-inline">
                    <button class="btn btn-sm btn-outline-danger"
                            asp-controller="SparePart" asp-action="Delete" asp-route-id="@item.Id">Delete</button>
                </form>
                <a class="btn btn-sm btn-outline-primary"
                   asp-controller="SparePart" asp-action="Update" asp-route-id="@item.Id">Update</a>
            </td>
        </tr>
    }
    </tbody>
    <caption>To add new item press <a class="btn btn-sm btn-primary" asp-controller="SparePart" asp-action="Add">Add</a></caption>
</table>

AutoParkWeb/Views/SparePart/Update.cshtml
@model SparePart
@{
    ViewData["Title"] = "Update - Spare part";
}
<div class="card">
    <div class="card-header"><h3>Update spare part</h3></div>
    <div class="card-body">
        <form asp-controller="SparePart" asp-action="Update" method="post">
            <input asp-for="Id" hidden>

            <div><span asp-validation-for="Name" class="text-danger"></span></div>
            <div class="form-group row">
                <label asp-for="Name" class="col-sm-3 col-form-label"></label>
                <div class="col-sm-9">
                    <input asp-for="Name" class="form-control">
                </div>
            </div>

            <div><span asp-validation-for="Description" class="text-danger"></span></div>
            <div class="form-group row">
                <label asp-for="Description" class="col-sm-3 col-form-label"></label>
                <div class="col-sm-9">
                    <input asp-for="Description" class="form-control">
                </div>
            </div>

            <div class="text-center">
                <button class="btn btn-block btn-primary mx-auto">Update</button>
            </div>
        </form>
    </div>
</div>