AutoParkWeb/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Permissions;
using System.Security.Principal;
using System.Threading.Tasks;
using AutoParkData.Model.Orders;
using AutoParkData.Repositories.Interfaces;
using AutoParkWeb.Models;
using AutoParkWeb.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AutoParkWeb.Controllers
{
    public class OrderController : Controller
    {
        private readonly IVehicleRepository vehicleRepository;
        private readonly IOrderRepository orderRepository;
        public OrderController(IOrderRepository orderRepository, IVehicleRepository vehicleRepository)
        {
            this.orderRepository = orderRepository;
            this.vehicleRepository = vehicleRepository;
        }

        /// <summary>
        /// Returns select list of Vehicles
        /// </summary>
        /// <returns></returns>
        private async Task<List<SelectListItem>> GetSelectListOfVehicles()
        {
            var vehicles = await vehicleRepository.GetVehicles();
            return vehicles.Select(vehicle =>
                new SelectListItem($"{vehicle.ModelName}: {vehicle.RegistrationNumber}", vehicle.Id.ToString())).ToList();
        }

        public async Task<IActionResult> Index(int id)
        {
            var order = await orderRepository.Get(id);
            return View(order);
        }

        public async Task<IActionResult> List()
        {
            var data = await orderRepository.GetOrders();
            return View(data);
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            ViewBag.VehicleList = await GetSelectListOfVehicles();
            return View(new Order());
        }

        [HttpPost]
        public async Task<IActionResult> Add(Order order)
        {
            await orderRepository.Add(order);
            return RedirectToAction(nameof(List));
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            ViewBag.VehicleList = await GetSelectListOfVehicles();

            var order = await orderRepository.Get(id);
            return View(order);
        }

        [HttpPost]
        public async Task<IActionResult> Update(Order order)
        {
            await orderRepository.Update(order);
            return RedirectToAction(nameof(List));
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            await orderRepository.Delete(id);

            return RedirectToAction(nameof(List));
        }

    }
}

AutoParkWeb/Controllers/OrderItemController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoParkData.Model.Orders;
using AutoParkData.Repositories.Interfaces;
using AutoParkWeb.Models.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AutoParkWeb.Controllers
{
    public class OrderItemController : Controller
    {
        private readonly IOrderItemRepository itemRepository;
        private readonly ISparePartRepository sparePartRepository;

        public OrderItemController(IOrderItemRepository itemRepository, ISparePartRepository sparePartRepository)
        {
            this.itemRepository = itemRepository;
            this.sparePartRepository = sparePartRepository;
        }

        /// <summary>
        /// Returns select list of SpareParts
        /// </summary>
        /// <returns></returns>
        private async Task<List<SelectListItem>> GetSelectListOfSpareParts()
        {
            var spareParts = await sparePartRepository.GetSpareParts();
            return spareParts.Select(part => new SelectListItem(part.Name, part.Id.ToString())).ToList();
        }

        [HttpGet]
        public async Task<IActionResult> Add(int orderId)
        {
            ViewBag.SparePartList = await GetSelectListOfSpareParts();
            return View(new OrderItem() { OrderId = orderId });
        }

        [HttpPost]
        public async Task<IActionResult> Add(OrderItem orderItem)
        {
            await itemRepository.Add(orderItem);
            return RedirectToAction("Index", "Order", new { id = orderItem.OrderId });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int orderId, int orderItemId)
        {
            await itemRepository.Delete(orderItemId);
            return RedirectToAction("Index", "Order", new { id = orderId });
        }

        [HttpGet]
        public async Task<IActionResult> Update(int orderId, int itemId)
        {
            ViewBag.SparePartList = await GetSelectListOfSpareParts();

            var item = await itemRepository.Get(itemId);
            return View(item);
        }

        [HttpPost]
        public async Task<IActionResult> Update(OrderItem orderItem)
        {
            await itemRepository.Update(orderItem);
            return RedirectToAction("Index", "Order", new { id = orderItem.OrderId });
        }

    }
}

AutoParkWeb/Views/Order/Add.cshtml
@model Order
@{
    ViewData["Title"] = "Add Order";
}

<div class="card">
    <div class="card-header"><h3>Add Order</h3></div>
    <div class="card-body">
        <div asp-validation-summary="All" class="text-danger"></div>
    
        <form asp-controller="Order" asp-action="Add" method="post">

            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Vehicle type id</label>
                <div class="col-sm-9">
                    <select class="form-control" asp-for="VehicleId" asp-items="@ViewBag.VehicleList"></select>
                </div>
            </div>

            <div><span asp-validation-for="Description" class="text-danger"></span></div>
            <div class="form-group row">
                <label asp-for="Description" class="col-sm-3 col-form-label"></label>
                <div class="col-sm-9">
                    <input asp-for="Description" class="form-control">
                </div>
            </div>

            <div class="text-center">
                <button class="btn btn-primary mx-auto">Add</button>
            </div>
        </form>
    </div>
</div>

AutoParkWeb/Views/Order/Index.cshtml
@model Order
@{
    ViewData["Title"] = "Add Order";
}

<div class="card">
    <div class="card-header">
        <h3>Order №@Model.Id : @Model.Description</h3>
    </div>
    <div class="card-body">
        <div class="card mb-3">
            <div class="card-header"><h4>Vehicle</h4></div>

            <div class="form-group ml-2">
                <label class="font-weight-bold">Id:</label>
                <text>@Model.TargetVehicle.Id</text>
            </div>

            <div class="form-group ml-2">
                <label class="font-weight-bold">Model Name:</label>
                <text>@Model.TargetVehicle.ModelName</text>
            </div>

            <div class="form-group ml-2">
                <label class="font-weight-bold">Registration number:</label>
                <text>@Model.TargetVehicle.RegistrationNumber</text>
            </div>
        </div>

        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Count</th>
                    <th>Actions</th>
                </tr>
            </thead>
            @foreach (var orderItem in Model.OrderItems)
            {
                <tr>
                    <td>@orderItem.Id</td>
                    <td>@orderItem.SparePart.Name</td>
                    <td>@orderItem.SparePart.Description</td>
                    <td>@orderItem.Count</td>
                    <td>
                        <form class="d-inline" asp-controller="OrderItem" asp-action="Delete"
                              asp-route-orderId="@Model.Id" , asp-route-orderItemId="@orderItem.Id">
                            <button class="btn btn-sm btn-outline-danger">Delete</button>
                        </form>

                        <a class="btn btn-sm btn-outline-primary" asp-controller="OrderItem" asp-action="Update"
                           asp-route-itemId="@orderItem.Id" asp-route-orderId="@Model.Id">Update</a>
                    </td>
                </tr>
            }
            <caption>
                Add new item: <a class="btn btn-sm btn-primary" asp-controller="OrderItem" asp-action="Add" asp-route-orderId="@Model.Id">Add</a>
            </caption>
        </table>
    </div>
</div>

AutoParkWeb/Views/Order/List.cshtml
@model IEnumerable<Order>
@{
    ViewData["Title"] = "Vehicle Types";
}


<table class="table">

    <thead>
        <tr>
            <th><strong>Id</strong></th>
            <th>Description</th>
            <th>Vehicle model name</th>
            <th>Vehicle registration number</th>
            <th>Spare parts count</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td><a asp-controller="Order" asp-action="Index" asp-route-id="@item.Id">@item.Id</a></td>
                <td>@item.Description</td>
                <td>@item.TargetVehicle.ModelName</td>
                <td>@item.TargetVehicle.RegistrationNumber</td>
                <td>@item.OrderItems.Count</td>
                <td>
                    <div>
                        <form class="d-inline" asp-controller="Order" asp-action="Delete" asp-route-id="@item.Id">
                            <button class="btn btn-sm btn-outline-danger">Delete</button>
                        </form>
                        <a class="btn btn-sm btn-outline-primary" asp-controller="Order" asp-action="Update" asp-route-id="@item.Id">Update</a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
    <caption>To add new item press <a class="btn btn-sm btn-primary" asp-controller="Order" asp-action="Add">Add</a></caption>
</table>

AutoParkWeb/Views/Order/Update.cshtml
@model Order
@{
    ViewData["Title"] = "Update Order";
}

<div class="card">
    <div class="card-header"><h3>Update Order</h3></div>
    <div class="card-body">
        <div asp-validation-summary="All" class="text-danger"></div>

        <form asp-controller="Order" asp-action="Update" method="post">
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Vehicle type id</label>
                <div class="col-sm-9">
                    <select class="form-control" asp-for="VehicleId" asp-items="@ViewBag.VehicleList"></select>
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="Description" class="col-sm-3 col-form-label"></label>
                <div class="col-sm-9">
                    <input asp-for="Description" class="form-control">
                </div>
            </div>
            <div class="text-center">
                <button class="btn btn-block btn-primary mx-auto">Update</button>
            </div>
        </form>
    </div>
</div>